version: '3.8' 

services:
  
  gerador-assinatura:
    build: .
    volumes:
      - .:/usr/src/app
    command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:5000", "--reload", "app:app"]

  # SERVIÇO 2: NGINX (REVERSE PROXY / FRONT-DOOR)
  nginx:
    image: nginx:stable-alpine # Usa uma imagem oficial e leve do Nginx
    ports:
      - "80:80"
    volumes:
      # Monta seu arquivo de configuração personalizado dentro do contêiner Nginx.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Monta sua pasta static para que o Nginx possa servir os arquivos diretamente.
      - ./static:/app/static
    depends_on:
      - gerador-assinatura # Garante que o serviço da aplicação inicie antes do Nginx.