# docker-compose.yml

version: '3.8'

services:
  # Serviço do Backend (Flask + Gunicorn)
  backend:
    build:
      context: . # Usa o Dockerfile na pasta atual
    # A porta 5000 não é mais exposta publicamente
    volumes:
      - .:/usr/src/app # Volume para desenvolvimento (opcional para produção)
    # env_file:
    #   - .env # Carrega variáveis de ambiente (como SECRET_KEY)

  # Serviço do Nginx (Serve o Frontend e atua como Proxy)
  nginx:
    image: nginx:stable-alpine
    ports:
      # A única porta exposta publicamente. Porta 80 do seu PC -> Porta 80 do Nginx
      - "80:80" 
    volumes:
      # Monta seu arquivo de configuração do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Monta seus arquivos estáticos para o Nginx servir
      - ./static:/usr/share/nginx/html/static 
      # Monta seu template HTML para o Nginx servir
      - ./templates:/usr/share/nginx/html 
    depends_on:
      - backend # Garante que o backend inicie antes do Nginx