name: CI/CD - Teste e Deploy

# Aciona o workflow em push ou pull request para as branches main e develop
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build_and_test: # Este job agora valida e testa ambos, backend e frontend
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código do repositório
      - uses: actions/checkout@v3

      - name: 2. Configurar Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 3. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Usar uma versão LTS
          cache: "npm"

      - name: 4. Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 5. Instalar dependências Node.js
        run: npm install

      - name: 6. Rodar Linter do Backend (Flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: 7. Rodar Linter do Frontend (ESLint)
        run: npm run lint

      - name: 8. Rodar Testes Unitários do Backend (Pytest)
        run: pytest

      - name: 9. Rodar Testes Unitários do Frontend (Jest)
        run: npm test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' # Deploy automático apenas para a branch 'main'

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          # Usa o token que você salvou nos segredos do GitHub
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
